services:

  # RFC翻訳結果を閲覧するためのWebページ
  nginx:
    container_name: rfctrans-nginx
    build:
      context: ./nginx
      dockerfile: Containerfile
    ports:
      - "11080:80"
    volumes:
      - ./html:/usr/share/nginx/html:z
    restart: always
