FROM python:3.12

ENV PYTHONIOENCODING utf-8

WORKDIR /opt/app/

RUN adduser --disabled-login mako && chown -R mako /opt/app/
USER mako

COPY ../requirements.txt /opt/app/
RUN pip install -r /opt/app/requirements.txt
COPY exec.py /opt/app/

EXPOSE 11080

CMD ["python", "exec.py"]
#CMD ["bash"]
